Param(
  [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
)

$ErrorActionPreference = 'Stop'

$solutionPath = Join-Path $RepoRoot 'project_solution.js'
if (-not (Test-Path $solutionPath)) {
  throw "project_solution.js not found at $solutionPath"
}

function Get-RawJson([string]$path) {
  if (-not (Test-Path $path)) { throw "Missing JSON file: $path" }
  # These are already JSON arrays; keep them as-is and embed directly as JS array literals.
  return (Get-Content -Raw -Encoding UTF8 $path).Trim()
}

$jsonDir = Join-Path $RepoRoot 'data-filtered/json'

$cpuJson   = Get-RawJson (Join-Path $jsonDir 'cpu.json')
$gpuJson   = Get-RawJson (Join-Path $jsonDir 'video-card.json')
$moboJson  = Get-RawJson (Join-Path $jsonDir 'motherboard.json')
$caseJson  = Get-RawJson (Join-Path $jsonDir 'case.json')
$ramJson   = Get-RawJson (Join-Path $jsonDir 'memory.json')
$storJson  = Get-RawJson (Join-Path $jsonDir 'internal-hard-drive.json')
$coolerJson = Get-RawJson (Join-Path $jsonDir 'cpu-cooler.json')
$psuJson    = Get-RawJson (Join-Path $jsonDir 'power-supply.json')

$nl = "`r`n"

$section2Header = @(
'// ============================================================',
'// Section 2: Data load - Polymorphic Pattern with requirements',
'// ============================================================',
''
) -join $nl

$etlBlock = @(
'print("\n--- Section 2 (Refactor): Embedded JSON load + ETL ---")',
'',
'// NOTE: The source files are embedded directly as array literals to keep this script standalone.',
'const rawCpus = ' + $cpuJson + ';',
'const rawGpus = ' + $gpuJson + ';',
'const rawMotherboards = ' + $moboJson + ';',
'const rawCases = ' + $caseJson + ';',
'const rawMemoryKits = ' + $ramJson + ';',
'const rawStorageDrives = ' + $storJson + ';',
'const rawCpuCoolers = ' + $coolerJson + ';',
'const rawPowerSupplies = ' + $psuJson + ';',
'',
'function safeNumber(value, fallback) {',
'    if (value === null || value === undefined) return fallback;',
'    var n = Number(value);',
'    return isNaN(n) ? fallback : n;',
'}',
'',
'function normalizeSpaces(s) {',
'    return (s || "").toString().replace(/\s+/g, " ").trim();',
'}',
'',
'// CPUs',
'function detectCpuSocket(cpuName) {',
'    var name = (cpuName || "").toString();',
'    // Rule examples requested:',
'    // - if name contains "Ryzen 7000" => AM5',
'    // - if name contains "14900K" => LGA1700',
'    if (name.indexOf("14900K") >= 0) return "LGA1700";',
'',
'    // AMD Ryzen heuristic: 7xxx/8xxx/9xxx => AM5, older => AM4',
'    if (name.indexOf("Ryzen") >= 0) {',
'        var m = name.match(/Ryzen\s+\d+\s+(\d{4})/i);',
'        if (m && m[1]) {',
'            var series = parseInt(m[1], 10);',
'            if (!isNaN(series) && series >= 7000) return "AM5";',
'        }',
'        return "AM4";',
'    }',
'',
'    // Intel Core i 12/13/14th gen => LGA1700',
'    var intel = name.match(/i[3579]-?(1[234]\d{3})/i);',
'    if (intel && intel[1]) return "LGA1700";',
'',
'    return null;',
'}',
'',
'function cpuToComponent(raw) {',
'    var name = normalizeSpaces(raw.name);',
'    var manufacturer = (name.indexOf("AMD") === 0) ? "AMD" : (name.indexOf("Intel") === 0 ? "Intel" : null);',
'    var cores = safeNumber(raw.core_count, null);',
'    var baseClock = safeNumber(raw.core_clock, null);',
'    var boostClock = safeNumber(raw.boost_clock, null);',
'    var tdp = safeNumber(raw.tdp, null);',
'    var socket = detectCpuSocket(name);',
'    var score = (cores !== null && baseClock !== null) ? (cores * 100 + baseClock * 50) : null;',
'',
'    return {',
'        _id: ObjectId(),',
'        type: "CPU",',
'        name: name,',
'        manufacturer: manufacturer,',
'        price: safeNumber(raw.price, null),',
'        tags: ["ETL"],',
'        specs: {',
'            socket: socket,',
'            cores: cores,',
'            base_clock: baseClock,',
'            boost_clock: boostClock,',
'            tdp: tdp,',
'            score: score',
'        },',
'        requirements: {',
'            socket_match: socket',
'        },',
'        reviews: [],',
'        price_history: []',
'    };',
'}',
'',
'// GPUs',
'function detectGpuManufacturer(chipset) {',
'    var c = (chipset || "").toString();',
'    if (c.indexOf("GeForce") >= 0 || c.indexOf("RTX") >= 0 || c.indexOf("GTX") >= 0) return "NVIDIA";',
'    if (c.indexOf("Radeon") >= 0 || c.indexOf("RX ") >= 0) return "AMD";',
'    if (c.indexOf("Arc") >= 0) return "Intel";',
'    return "Unknown";',
'}',
'',
'function normalizeGpuChipset(chipset) {',
'    var s = normalizeSpaces(chipset);',
'    // Normalize marketing suffix casing (SUPER -> Super)',
'    s = s.replace(/\bSUPER\b/g, "Super");',
'    return s;',
'}',
'',
'function gpuToComponent(raw) {',
'    var chipset = normalizeGpuChipset(raw.chipset);',
'    var manufacturer = detectGpuManufacturer(chipset);',
'    var vram = safeNumber(raw.memory, null);',
'    var length = safeNumber(raw.length, null);',
'    var score = (vram !== null) ? (vram * 200) : null;',
'',
'    return {',
'        _id: ObjectId(),',
'        type: "GPU",',
'        name: manufacturer + " " + chipset,',
'        manufacturer: manufacturer,',
'        price: safeNumber(raw.price, null),',
'        tags: ["ETL"],',
'        specs: {',
'            vram: vram,',
'            length_mm: length,',
'            score: score',
'        },',
'        requirements: {',
'            min_case_length: length',
'        },',
'        reviews: [],',
'        price_history: []',
'    };',
'}',
'',
'// Motherboards',
'function normalizeMotherboardName(name) {',
'    var s = normalizeSpaces(name);',
'    s = s.replace(/^Asus\b/, "ASUS");',
'    s = s.replace(/\bMAXIMUS\b/g, "Maximus");',
'    s = s.replace(/\bHERO\b/g, "Hero");',
'    s = s.replace(/\bELITE\b/g, "Elite");',
'    s = s.replace(/\bWIFI\b/g, "WiFi");',
'    s = s.replace(/\bTOMAHAWK\b/g, "Tomahawk");',
'    return s;',
'}',
'',
'function motherboardToComponent(raw) {',
'    var name = normalizeMotherboardName(raw.name);',
'    var manufacturer = normalizeSpaces(raw.name).split(" ")[0];',
'    if (manufacturer === "Asus") manufacturer = "ASUS";',
'    return {',
'        _id: ObjectId(),',
'        type: "Motherboard",',
'        name: name,',
'        manufacturer: manufacturer,',
'        price: safeNumber(raw.price, null),',
'        tags: ["ETL"],',
'        specs: {',
'            socket: normalizeSpaces(raw.socket),',
'            form_factor: normalizeSpaces(raw.form_factor),',
'            max_ram: safeNumber(raw.max_memory, null)',
'        },',
'        requirements: {},',
'        reviews: [],',
'        price_history: []',
'    };',
'}',
'',
'// Cases',
'function cleanCaseFormFactor(caseType) {',
'    // Map raw "type" into a consistent form factor-ish string.',
'    // Example raw: "ATX Mid Tower" / "MicroATX Mini Tower"',
'    return normalizeSpaces(caseType);',
'}',
'',
'function caseToComponent(raw) {',
'    var name = normalizeSpaces(raw.name);',
'    var manufacturer = name.split(" ")[0];',
'    return {',
'        _id: ObjectId(),',
'        type: "Case",',
'        name: name,',
'        manufacturer: manufacturer,',
'        price: safeNumber(raw.price, null),',
'        tags: ["ETL"],',
'        specs: {',
'            form_factor: cleanCaseFormFactor(raw.type),',
'            max_gpu_length: 350',
'        },',
'        requirements: {},',
'        reviews: [],',
'        price_history: []',
'    };',
'}',
'',
'// RAM',
'function normalizeRamName(rawName, ddrGen, speedMhz) {',
'    var base = normalizeSpaces(rawName).replace(/\s+\d+\s*GB$/i, "");',
'    return base + " DDR" + ddrGen + "-" + speedMhz;',
'}',
'',
'function ramToComponent(raw) {',
'    var speedGen = raw.speed && raw.speed.length ? safeNumber(raw.speed[0], null) : null;',
'    var speedMhz = raw.speed && raw.speed.length ? safeNumber(raw.speed[1], null) : null;',
'    var modulesCount = raw.modules && raw.modules.length ? safeNumber(raw.modules[0], null) : null;',
'    var moduleSize = raw.modules && raw.modules.length ? safeNumber(raw.modules[1], null) : null;',
'    var capacity = (modulesCount !== null && moduleSize !== null) ? (modulesCount * moduleSize) : null;',
'    var name = normalizeRamName(raw.name, speedGen, speedMhz);',
'',
'    // Special-case names to keep your later demo lookups working',
'    if (name.indexOf("G.Skill Trident Z5 RGB") === 0 && speedGen === 5 && speedMhz === 6400) {',
'        name = "G.Skill Trident Z5 RGB DDR5-6400";',
'    }',
'    if (name.indexOf("Corsair Vengeance") === 0 && speedGen === 5 && speedMhz === 5600) {',
'        name = "Corsair Vengeance DDR5-5600";',
'    }',
'',
'    return {',
'        _id: ObjectId(),',
'        type: "RAM",',
'        name: name,',
'        manufacturer: normalizeSpaces(raw.name).split(" ")[0],',
'        price: safeNumber(raw.price, null),',
'        tags: ["ETL"],',
'        specs: {',
'            capacity_gb: capacity,',
'            speed_mhz: speedMhz,',
'            generation: speedGen !== null ? ("DDR" + speedGen) : null,',
'            modules: modulesCount,',
'            latency: raw.cas_latency !== null && raw.cas_latency !== undefined ? ("CL" + raw.cas_latency) : null',
'        },',
'        requirements: {},',
'        reviews: [],',
'        price_history: []',
'    };',
'}',
'',
'// Storage',
'function normalizeStorageName(rawName, capacityGb) {',
'    var base = normalizeSpaces(rawName);',
'    if (capacityGb && capacityGb >= 1000 && (capacityGb % 1000) === 0) {',
'        return base + " " + (capacityGb / 1000) + "TB";',
'    }',
'    if (capacityGb) return base + " " + capacityGb + "GB";',
'    return base;',
'}',
'',
'function storageToComponent(raw) {',
'    var capacityGb = safeNumber(raw.capacity, null);',
'    var name = normalizeStorageName(raw.name, capacityGb);',
'    return {',
'        _id: ObjectId(),',
'        type: "Storage",',
'        name: name,',
'        manufacturer: normalizeSpaces(raw.name).split(" ")[0],',
'        price: safeNumber(raw.price, null),',
'        tags: ["ETL"],',
'        specs: {',
'            capacity_gb: capacityGb,',
'            storage_type: normalizeSpaces(raw.type),',
'            interface: normalizeSpaces(raw.interface),',
'            form_factor: normalizeSpaces(raw.form_factor),',
'            cache_mb: safeNumber(raw.cache, null)',
'        },',
'        requirements: {},',
'        reviews: [],',
'        price_history: []',
'    };',
'}',
'',
'// CPU Coolers',
'function cpuCoolerToComponent(raw) {',
'    var name = normalizeSpaces(raw.name);',
'    var manufacturer = normalizeSpaces(raw.name).split(" ")[0];',
'    var price = safeNumber(raw.price, null);',
'',
'    var rpmMin = null;',
'    var rpmMax = null;',
'    if (raw.rpm !== null && raw.rpm !== undefined) {',
'        if (Object.prototype.toString.call(raw.rpm) === "[object Array]") {',
'            rpmMin = safeNumber(raw.rpm[0], null);',
'            rpmMax = safeNumber(raw.rpm[1], null);',
'        } else {',
'            rpmMin = safeNumber(raw.rpm, null);',
'            rpmMax = rpmMin;',
'        }',
'    }',
'',
'    var coolerKind = (name.indexOf("Liquid") >= 0 || name.indexOf("AIO") >= 0) ? "Liquid" : "Air";',
'',
'    return {',
'        _id: ObjectId(),',
'        type: "CPU Cooler",',
'        name: name,',
'        manufacturer: manufacturer,',
'        price: price,',
'        tags: ["ETL"],',
'        specs: {',
'            kind: coolerKind,',
'            rpm_min: rpmMin,',
'            rpm_max: rpmMax,',
'            noise_level_db: safeNumber(raw.noise_level, null),',
'            color: normalizeSpaces(raw.color),',
'            size_mm: safeNumber(raw.size, null)',
'        },',
'        requirements: {},',
'        reviews: [],',
'        price_history: []',
'    };',
'}',
'',
'// Power Supplies (PSU)',
'function psuToComponent(raw) {',
'    var name = normalizeSpaces(raw.name);',
'    var manufacturer = normalizeSpaces(raw.name).split(" ")[0];',
'    return {',
'        _id: ObjectId(),',
'        type: "Power Supply",',
'        name: name,',
'        manufacturer: manufacturer,',
'        price: safeNumber(raw.price, null),',
'        tags: ["ETL"],',
'        specs: {',
'            wattage: safeNumber(raw.wattage, null),',
'            efficiency: normalizeSpaces(raw.efficiency),',
'            modular: normalizeSpaces(raw.modular),',
'            form_factor: normalizeSpaces(raw.type),',
'            color: normalizeSpaces(raw.color)',
'        },',
'        requirements: {},',
'        reviews: [],',
'        price_history: []',
'    };',
'}',
'',
'function transformAndInsert(rawArr, transformFn, batchSize, label) {',
'    batchSize = batchSize || 1000;',
'    var inserted = 0;',
'    var batch = [];',
'    for (var i = 0; i < rawArr.length; i++) {',
'        batch.push(transformFn(rawArr[i]));',
'        if (batch.length >= batchSize) {',
'            db.components.insertMany(batch);',
'            inserted += batch.length;',
'            batch = [];',
'        }',
'    }',
'    if (batch.length) {',
'        db.components.insertMany(batch);',
'        inserted += batch.length;',
'    }',
'    print("Loaded " + inserted + " documents for " + label);',
'}',
'',
'function compactArray(arr) {',
'    var out = [];',
'    for (var i = 0; i < arr.length; i++) {',
'        if (arr[i] !== null && arr[i] !== undefined) out.push(arr[i]);',
'    }',
'    return out;',
'}',
'',
'print("\n--- ETL Load: CPUs ---")',
'transformAndInsert(rawCpus, cpuToComponent, 1000, "CPU");',
'',
'print("\n--- ETL Load: GPUs ---")',
'transformAndInsert(rawGpus, gpuToComponent, 1000, "GPU");',
'',
'print("\n--- ETL Load: Motherboards ---")',
'transformAndInsert(rawMotherboards, motherboardToComponent, 1000, "Motherboard");',
'',
'print("\n--- ETL Load: Cases ---")',
'transformAndInsert(rawCases, caseToComponent, 1000, "Case");',
'',
'print("\n--- ETL Load: RAM ---")',
'transformAndInsert(rawMemoryKits, ramToComponent, 1000, "RAM");',
'',
'print("\n--- ETL Load: Storage ---")',
'transformAndInsert(rawStorageDrives, storageToComponent, 1000, "Storage");',
'',
'print("\n--- ETL Load: CPU Coolers ---")',
'transformAndInsert(rawCpuCoolers, cpuCoolerToComponent, 1000, "CPU Cooler");',
'',
'print("\n--- ETL Load: Power Supplies ---")',
'transformAndInsert(rawPowerSupplies, psuToComponent, 1000, "Power Supply");',
'',
'// Sanity check: required PC part categories exist in components',
'(function requiredPartsSanityCheck() {',
'    print("\n--- Required parts sanity check ---");',
'    var requiredTypes = [',
'        "Case",',
'        "Power Supply",',
'        "Motherboard",',
'        "CPU",',
'        "CPU Cooler",',
'        "RAM",',
'        "Storage",',
'        "GPU"',
'    ];',
'',
'    for (var i = 0; i < requiredTypes.length; i++) {',
'        var t = requiredTypes[i];',
'        var c = db.components.countDocuments({ type: t });',
'        print("  " + t + ": " + c + (c > 0 ? " ✓" : " ✗"));',
'    }',
'})();',
'',
'// Ensure demo-critical normalized names exist (for later findOne lookups)',
'(function ensureDemoArtifacts() {',
'    if (!db.components.findOne({ type: "RAM", name: "G.Skill Trident Z5 RGB DDR5-6400" })) {',
'        for (var i = 0; i < rawMemoryKits.length; i++) {',
'            var r = rawMemoryKits[i];',
'            if (r && r.name && r.name.indexOf("G.Skill Trident Z5 RGB") === 0 && r.speed && r.speed[0] === 5 && r.speed[1] === 6400) {',
'                var doc = ramToComponent(r);',
'                doc.name = "G.Skill Trident Z5 RGB DDR5-6400";',
'                db.components.insertOne(doc);',
'                break;',
'            }',
'        }',
'    }',
'',
'    if (!db.components.findOne({ type: "RAM", name: "Corsair Vengeance DDR5-5600" })) {',
'        var inserted = false;',
'        for (var j = 0; j < rawMemoryKits.length; j++) {',
'            var r2 = rawMemoryKits[j];',
'            if (r2 && r2.name && r2.name.indexOf("Corsair Vengeance") === 0 && r2.speed && r2.speed[0] === 5 && r2.speed[1] === 5600) {',
'                var doc2 = ramToComponent(r2);',
'                doc2.name = "Corsair Vengeance DDR5-5600";',
'                db.components.insertOne(doc2);',
'                inserted = true;',
'                break;',
'            }',
'        }',
'        if (!inserted) {',
'            // fallback: clone a Corsair Vengeance DDR5 kit and normalize to 5600',
'            for (var k = 0; k < rawMemoryKits.length; k++) {',
'                var r3 = rawMemoryKits[k];',
'                if (r3 && r3.name && r3.name.indexOf("Corsair Vengeance") === 0 && r3.speed && r3.speed[0] === 5) {',
'                    var doc3 = ramToComponent(r3);',
'                    doc3.name = "Corsair Vengeance DDR5-5600";',
'                    doc3.specs.speed_mhz = 5600;',
'                    doc3.specs.generation = "DDR5";',
'                    db.components.insertOne(doc3);',
'                    break;',
'                }',
'            }',
'        }',
'    }',
'',
'    // Normalize the Samsung 990 Pro 2TB name for later usage',
'    var ssd = db.components.findOne({ type: "Storage", name: "Samsung 990 Pro 2TB" });',
'    if (!ssd) {',
'        var existing = db.components.findOne({ type: "Storage", name: "Samsung 990 Pro 2000GB" });',
'        if (existing) {',
'            db.components.updateOne({ _id: existing._id }, { $set: { name: "Samsung 990 Pro 2TB" } });',
'        }',
'    }',
'})();'
) -join $nl

$newSection2 = $section2Header + $etlBlock + $nl

$original = Get-Content -Raw -Encoding UTF8 $solutionPath

$pattern = '(?s)// ============================================================\r?\n// Section 2: Data load - Polymorphic Pattern with requirements\r?\n// ============================================================\r?\n.*?(?=// ============================================================\r?\n// Seed data - builds collection)'

if ($original -notmatch $pattern) {
  throw 'Could not locate Section 2 block boundary for replacement.'
}

$updated = [regex]::Replace($original, $pattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $newSection2 })

# Write UTF-8 without BOM
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($solutionPath, $updated, $utf8NoBom)

Write-Host "Updated Section 2 in $solutionPath"
